Models/ErrorViewModel.cs
using System;

namespace ModelDemoDNCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Expense")]
        [Required]
        public string ExpenseName { get; set; }

        [Required]
        [Range(1,int.MaxValue,ErrorMessage ="Amount must be greater than 0")]
        public int Amount { get; set; }
    }
}

Models/ExpenseType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Models
{
    public class ExpenseType
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }


    }
}

Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Borrower { get; set; }

        public string Lender { get; set; }
        [DisplayName("Item Name")]
        public string ItemName { get; set; }


    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }

        public int Age { get; set; }
    }
}

Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;

using ModelDemoDNCore.Data;
using ModelDemoDNCore.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExpenseController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Expense> objList = _db.Expenses;
            return View(objList);
            //return View();
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense obj)
        {
            if (ModelState.IsValid)
            {
                _db.Expenses.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //get Delete
        public IActionResult Delete(int? id)
        {
            if (id ==null || id==0)
            {
                return NotFound();
            }
            var obj=_db.Expenses.Find(id);
            if (obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj=_db.Expenses.Find(id);
            if (obj==null)
            {
                return NotFound();
            }

                _db.Expenses.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");

        }

        //get Update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expense obj)
        {
            if (ModelState.IsValid)
            {
                _db.Expenses.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

Controllers/ExpenseTypeController.cs
using Microsoft.AspNetCore.Mvc;

using ModelDemoDNCore.Data;
using ModelDemoDNCore.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Controllers
{
    public class ExpenseTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExpenseTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ExpenseType> objList = _db.ExpensesType;
            return View(objList);
            //return View();
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpensesType.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //get Delete
        public IActionResult Delete(int? id)
        {
            if (id ==null || id==0)
            {
                return NotFound();
            }
            var obj=_db.ExpensesType.Find(id);
            if (obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj=_db.ExpensesType.Find(id);
            if (obj==null)
            {
                return NotFound();
            }

                _db.ExpensesType.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");

        }

        //get Update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ExpensesType.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpensesType.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using ModelDemoDNCore.Models;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;

using ModelDemoDNCore.Data;
using ModelDemoDNCore.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelDemoDNCore.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ItemController(ApplicationDbContext db)
        {
            _db=db;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList=_db.Item;
            return View(objList);
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Item.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Expense/Create.cshtml
@model ModelDemoDNCore.Models.Expense

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                       <label asp-for="ExpenseName"></label>
                     
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create"/>
                        </div>
                        <div class="col">
                            <a class=" btn btn-danger w-75" asp-action="Index">My Borrowed item</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{ 
    @{<partial name="_ValidationScriptsPartial"/>}
}

Views/Expense/Delete.cshtml
@model ModelDemoDNCore.Models.Expense

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>

                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger btn-info w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a class=" btn  btn-success w-75" asp-action="Index" >Back</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Expense/Index.cshtml
@model IEnumerable<ModelDemoDNCore.Models.Expense>

<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Expense  List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expense" asp-action="Create" class="btn btn-primary"> Create new  Expense</a>
           
        </div>

    </div>
    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Expense
                    </th>
                    <th>
                        Amount
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var Expense in Model)
                {
                <tr>
                    <td width="30%">@Expense.ExpenseName</td>
                    <td width="30%">@Expense.Amount</td>
                    <td width="40%">
                        <div class="col-6 text-right">
                            <a asp-controller="Expense" asp-action="Update" asp-route-id="@Expense.Id" class="btn btn-primary">Update</a>
                            <a asp-controller="Expense" asp-action="Delete" asp-route-id="@Expense.Id" class="btn btn-primary">Delete</a>
                        </div>
                    </td>
                </tr>

                }

            </tbody>
        </table>      
    }
    else
    {
        <p>No item Create yet</p>

    }
</div>

Views/Expense/Update.cshtml
@model ModelDemoDNCore.Models.Expense

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">


        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>

                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a class=" btn btn-danger w-75" asp-action="Index">My Borrowed item</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/ExpenseType/Create.cshtml
@model ModelDemoDNCore.Models.ExpenseType

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                       <label asp-for="Name"></label>
                     
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create"/>
                        </div>
                        <div class="col">
                            <a class=" btn btn-danger w-75" asp-action="Index">My Borrowed item</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{ 
    @{<partial name="_ValidationScriptsPartial"/>}
}

Views/ExpenseType/Delete.cshtml
@model ModelDemoDNCore.Models.ExpenseType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger btn-info w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a class=" btn  btn-success w-75" asp-action="Index" >Back</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/ExpenseType/Index.cshtml
@model IEnumerable<ModelDemoDNCore.Models.ExpenseType>

<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Expense  List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ExpenseType" asp-action="Create" class="btn btn-primary"> Create new  Expense Type</a>
           
        </div>

    </div>
    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Expense
                    </th>
                    <th>
                         change
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var ExpenseType in Model)
                {
                <tr>
                    <td width="30%">@ExpenseType.Name
                    <td width="40%">
                        <div class="col-6 text-right">
                            <a asp-controller="ExpenseType" asp-action="Update" asp-route-id="@ExpenseType.Id" class="btn btn-primary">Update</a>
                            <a asp-controller="ExpenseType" asp-action="Delete" asp-route-id="@ExpenseType.Id" class="btn btn-primary">Delete</a>
                        </div>
                    </td>
                </tr>

                }

            </tbody>
        </table>      
    }
    else
    {
        <p>No item Create yet</p>

    }
</div>

Views/ExpenseType/Update.cshtml
@model ModelDemoDNCore.Models.ExpenseType

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">


        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a class=" btn btn-danger w-75" asp-action="Index">My Borrowed item</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Item/Create.cshtml
@model ModelDemoDNCore.Models.Item

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                       <label asp-for="ItemName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemName" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Borrower" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Lender" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 text-center row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create"/>
                        </div>
                        <div class="col">
                            <a class=" btn btn-danger w-75" asp-action="Index">My Borrowed item</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</form>

Views/Item/Index.cshtml
@model IEnumerable<ModelDemoDNCore.Models.Item>

<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Item" asp-action="Create"class="btn btn-primary"> Create new Item</a>
           
        </div>

    </div>
    @if(Model.Count()>0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Item Name
                    </th>
                    <th>
                        Borrower
                    </th>
                    <th>
                        Lender
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="30%">@item.ItemName</td>
                        <td width="30%">@item.Lender</td>
                        <td width="30%">@item.Borrower</td>
  
                    </tr>

                }

            </tbody>
        </table>      
    }
    else
    {
        <p>No item Create yet</p>

    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelDemoDNCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModelDemoDNCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My  Expense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseType" asp-action="Index">My  Expense type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ModelDemoDNCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/View.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>